using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DataAccessLayer.Contexts.Models
{
    public class Product
    {
        public Product()
        {
            CreateDate = DateTime.Now;
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; private set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public string Details { get; set; }

        [BsonDateTimeOptions] public DateTime CreateDate { get; }
    }
}
