using System;

namespace DomainModels
{
    public class Product
    {
        // [BsonId]
        //// standard BSonId generated by MongoDb
        //public ObjectId InternalId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public string Details { get; set; }
    }
}
